apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: plantr
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  namespace: plantr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          name: kafka
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: plantr-kafka-volume
              mountPath: /var/lib/kafka/data
              subPath: kafka
      volumes:
        - name: plantr-kafka-volume
          persistentVolumeClaim:
            claimName: plantr-kafka-volume-claim
